//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteAPP.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ClienteAPP.ServiceReference1.HelloWorldResponse HelloWorld(ClienteAPP.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteAPP.ServiceReference1.HelloWorldResponse> HelloWorldAsync(ClienteAPP.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/suma", ReplyAction="*")]
        decimal suma(decimal n1, decimal n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/suma", ReplyAction="*")]
        System.Threading.Tasks.Task<decimal> sumaAsync(decimal n1, decimal n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/resta", ReplyAction="*")]
        decimal resta(decimal n1, decimal n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/resta", ReplyAction="*")]
        System.Threading.Tasks.Task<decimal> restaAsync(decimal n1, decimal n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/multiplicacion", ReplyAction="*")]
        decimal multiplicacion(decimal n1, decimal n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/multiplicacion", ReplyAction="*")]
        System.Threading.Tasks.Task<decimal> multiplicacionAsync(decimal n1, decimal n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/division", ReplyAction="*")]
        decimal division(decimal n1, decimal n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/division", ReplyAction="*")]
        System.Threading.Tasks.Task<decimal> divisionAsync(decimal n1, decimal n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Areacirculo", ReplyAction="*")]
        double Areacirculo(double n1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Areacirculo", ReplyAction="*")]
        System.Threading.Tasks.Task<double> AreacirculoAsync(double n1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Areacuadrado", ReplyAction="*")]
        decimal Areacuadrado(decimal n1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Areacuadrado", ReplyAction="*")]
        System.Threading.Tasks.Task<decimal> AreacuadradoAsync(decimal n1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Areatriangulo", ReplyAction="*")]
        decimal Areatriangulo(decimal n1, decimal n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Areatriangulo", ReplyAction="*")]
        System.Threading.Tasks.Task<decimal> AreatrianguloAsync(decimal n1, decimal n2);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ClienteAPP.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ClienteAPP.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteAPP.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ClienteAPP.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : ClienteAPP.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<ClienteAPP.ServiceReference1.WebService1Soap>, ClienteAPP.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteAPP.ServiceReference1.HelloWorldResponse ClienteAPP.ServiceReference1.WebService1Soap.HelloWorld(ClienteAPP.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ClienteAPP.ServiceReference1.HelloWorldRequest inValue = new ClienteAPP.ServiceReference1.HelloWorldRequest();
            inValue.Body = new ClienteAPP.ServiceReference1.HelloWorldRequestBody();
            ClienteAPP.ServiceReference1.HelloWorldResponse retVal = ((ClienteAPP.ServiceReference1.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteAPP.ServiceReference1.HelloWorldResponse> ClienteAPP.ServiceReference1.WebService1Soap.HelloWorldAsync(ClienteAPP.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteAPP.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            ClienteAPP.ServiceReference1.HelloWorldRequest inValue = new ClienteAPP.ServiceReference1.HelloWorldRequest();
            inValue.Body = new ClienteAPP.ServiceReference1.HelloWorldRequestBody();
            return ((ClienteAPP.ServiceReference1.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        public decimal suma(decimal n1, decimal n2) {
            return base.Channel.suma(n1, n2);
        }
        
        public System.Threading.Tasks.Task<decimal> sumaAsync(decimal n1, decimal n2) {
            return base.Channel.sumaAsync(n1, n2);
        }
        
        public decimal resta(decimal n1, decimal n2) {
            return base.Channel.resta(n1, n2);
        }
        
        public System.Threading.Tasks.Task<decimal> restaAsync(decimal n1, decimal n2) {
            return base.Channel.restaAsync(n1, n2);
        }
        
        public decimal multiplicacion(decimal n1, decimal n2) {
            return base.Channel.multiplicacion(n1, n2);
        }
        
        public System.Threading.Tasks.Task<decimal> multiplicacionAsync(decimal n1, decimal n2) {
            return base.Channel.multiplicacionAsync(n1, n2);
        }
        
        public decimal division(decimal n1, decimal n2) {
            return base.Channel.division(n1, n2);
        }
        
        public System.Threading.Tasks.Task<decimal> divisionAsync(decimal n1, decimal n2) {
            return base.Channel.divisionAsync(n1, n2);
        }
        
        public double Areacirculo(double n1) {
            return base.Channel.Areacirculo(n1);
        }
        
        public System.Threading.Tasks.Task<double> AreacirculoAsync(double n1) {
            return base.Channel.AreacirculoAsync(n1);
        }
        
        public decimal Areacuadrado(decimal n1) {
            return base.Channel.Areacuadrado(n1);
        }
        
        public System.Threading.Tasks.Task<decimal> AreacuadradoAsync(decimal n1) {
            return base.Channel.AreacuadradoAsync(n1);
        }
        
        public decimal Areatriangulo(decimal n1, decimal n2) {
            return base.Channel.Areatriangulo(n1, n2);
        }
        
        public System.Threading.Tasks.Task<decimal> AreatrianguloAsync(decimal n1, decimal n2) {
            return base.Channel.AreatrianguloAsync(n1, n2);
        }
    }
}
